### ISSUE TITLE
bitcoin-api-0.12.0 can't builds its Haddock documentation

### ISSUE THREAD

**Issue by peti** [solatis/haskell-bitcoin-api#2]
```
src/Network/Bitcoin/Api/Wallet.hs:49:39-62:
’   parse error on input ‘-- | Our client context
```

**Comment by solatis** [comment]
I'm so sorry, what a silly mistake. I'll make sure to include a travis check for this.

**Comment by peti** [comment]
Will you release a new version?

**Comment by solatis** [comment]
Yeah I'm waiting for Travis to pass, I'll release a bugfix version right after.

**Comment by solatis** [comment]
http://hackage.haskell.org/package/bitcoin-api-0.12.1
