### ISSUE TITLE
JSONError "Error in $.result.balance: expected Integer, encountered floating number

### ISSUE THREAD

**Issue by ketzacoatl** [solatis/haskell-bitcoin-api#5]
Hi, thanks for your work on this library. I created a simple demo using the `bitcoin-api` package, and based off https://github.com/solatis/haskell-bitcoin-api/blob/master/test/Network/Bitcoin/Api/WalletSpec.hs, the demo is https://github.com/ketzacoatl/btc-monitor/blob/master/src/Main.hs. It compiles just fine, but at runtime I get this funny error I don't know what to do about:

```
Now sending JSON command: "{\"jsonrpc\":\"2.0\",\"params\":[\"mywallet\"],\"method\":\"getaccount\",\"id\":1}"
Now sending JSON command: "{\"jsonrpc\":\"2.0\",\"params\":[1,false],\"method\":\"listaccounts\",\"id\":1}"
Now sending JSON command: "{\"jsonrpc\":\"2.0\",\"params\":[],\"method\":\"getinfo\",\"id\":1}"
btc-trx-monitor: JSONError "Error in $.result.balance: expected Integer, encountered floating number 1.3"
```

This `1.3` is coming from `bitcoind` when I query a real wallet that has BTC in it from a faucet (this is on the testnet).

Am I doing something wrong, or is there an error in the library? When I review the test specs, I'm not sure I see coverage for floating point numbers.

**Comment by runeksvendsen** [comment]
Looks like there’s an error in the library. Everywhere else, the type `Data.Bitcoin.Types.Btc` is used for bitcoin amounts, but in `BitcoinInfo` an `Integer` is used for some reason.

Could you try changing the type of the `_balance` field in `BitcoinInfo` (https://github.com/solatis/haskell-bitcoin-api/blob/4985c797c4811110b2288d5770692810deb80cb4/src/Network/Bitcoin/Api/Misc.hs#L35) from `Integer` to `BT.Btc`?

As far as I can see, that should fix it.

**Comment by ketzacoatl** [comment]
That seemed like an easy update, so I started making it, but it took me down a bit of a rabbit hole with an import for `StatusCodeException`, see: https://github.com/ketzacoatl/haskell-bitcoin-api/blob/patch-1/src/Network/Bitcoin/Api/Internal.hs#L18 and https://github.com/ketzacoatl/haskell-bitcoin-api/blob/patch-1/src/Network/Bitcoin/Api/Internal.hs#L92, which now throws this error on me:

```
haskell-bitcoin-api/src/Network/Bitcoin/Api/Internal.hs:92:20-47: error:
        • The constructor ‘StatusCodeException’ should have 2 arguments, but has been given 3
        • In the pattern: StatusCodeException _ hdrL _
          In the pattern: Left ex@(StatusCodeException _ hdrL _)
          In a case alternative:
              Left ex@(StatusCodeException _ hdrL _)
                -> throwNothing (hdrM >>= decode . BL.fromStrict)
                where
                    hdrM = lookup "X-Response-Body-Start" hdrL
                    throwNothing = maybe (E.throwM (ex :: HttpException)) return
       |
    92 |           Left ex@(StatusCodeException _ hdrL _) ->
```

cc @runeksvendsen

**Comment by runeksvendsen** [comment]
I vaguely remember encountering that error myself. If I recall correctly, a breaking changes was made to `http-client` with regards to the `StatusCodeException` constructor. 

What version of `http-client` are you compiling with?

**Comment by ketzacoatl** [comment]
Ah, that makes more sense. I am building with stack and stackage, LTS-10.0, so I believe `http-client` is this at 0.5.7.1: https://www.stackage.org/lts-10.0/package/http-client-0.5.7.1

@runeksvendsen, is it reasonable to upgrade the library to use the latest release of `http-client`? I'm not sure I'll be able to figure it out, but I will see if I can make a PR.

**Comment by ketzacoatl** [comment]
OK, with @norfairking's help, I've gotten `master` to build with the latest release of `http-client` - see the PR linked above ^

**Comment by ketzacoatl** [comment]
@runeksvendsen would you agree it makes sense to cut a new release with a minor version bump?

**Comment by ketzacoatl** [comment]
This ought to be good to close

**Comment by runeksvendsen** [comment]
@ketzacoatl I'm fine with a new release, although I don't have the time -- nor the Hackage access rights -- to do it currently.

@solatis Could you be convinced to prepare a new release, or upload one from a person who has the time/knowledge to prepare one?

**Comment by solatis** [comment]
I'll take a look at it tomorrow!

**Comment by ketzacoatl** [comment]
Great, thanks @solatis and @runeksvendsen! I am also happy to help in any way that I can, just let me know.
